import { RATIO_FAMILIES, type RatioDef, type RatioFamily } from "./types";

export { RATIO_FAMILIES };
export type { RatioDef, RatioFamily, RatioUnit, RatioDirection, AveragingMode } from "./types";

/** Written out rather than aliased, because the expression parser knows only line items and ratios. */
const EBITDA = "(operating_income + depreciation_amortisation)";
const TOTAL_DEBT = "(short_term_debt + long_term_debt)";

/**
 * Figures a source may present either as a negative or as a magnitude, depending on the
 * statement's convention. Ratios read these as magnitudes.
 *
 * This is a fixed list, never a rule about the sign of a value: a company reporting net
 * interest income under `interest_expense` has a genuinely negative figure, and flipping
 * it because it is negative would hide that rather than surface it.
 */
export const MAGNITUDE_KEYS: readonly string[] = [
  "interest_expense",
  "capital_expenditures",
  "income_tax_expense",
  "cost_of_revenue",
  "operating_expenses",
  "dividends_paid",
];

export const RATIOS: readonly RatioDef[] = [
  // ---- Liquidity ----
  {
    key: "current_ratio",
    family: "liquidity",
    label: "Current ratio",
    expression: "total_current_assets / total_current_liabilities",
    unit: "x",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Current assets divided by current liabilities. Measures whether everything the company expects to turn into cash within a year covers everything it owes within a year.",
    caveat:
      "A high figure can mean idle inventory or uncollected receivables rather than strength. Read it with the efficiency ratios.",
    denominatorMustBePositive: false,
  },
  {
    key: "quick_ratio",
    family: "liquidity",
    label: "Quick ratio",
    expression:
      "(cash_and_equivalents + short_term_investments + accounts_receivable) / total_current_liabilities",
    unit: "x",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Cash, short-term investments and receivables divided by current liabilities. The current ratio with inventory and prepaid items stripped out, on the view that they cannot be converted to cash quickly.",
    caveat:
      "Treats every receivable as collectable. A business with ageing receivables looks more liquid here than it is.",
    denominatorMustBePositive: false,
  },
  {
    key: "cash_ratio",
    family: "liquidity",
    label: "Cash ratio",
    expression: "(cash_and_equivalents + short_term_investments) / total_current_liabilities",
    unit: "x",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Cash and marketable securities divided by current liabilities. The most conservative liquidity test: what could be settled today without collecting a thing.",
    caveat:
      "Almost every healthy company sits well below 1.0 here. A low figure is normal, not a warning on its own.",
    denominatorMustBePositive: false,
  },
  {
    key: "working_capital",
    family: "liquidity",
    label: "Working capital",
    expression: "total_current_assets - total_current_liabilities",
    unit: "currency",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Current assets less current liabilities. The absolute cushion between short-term resources and short-term obligations, in currency rather than as a multiple.",
    caveat:
      "An absolute figure, so it is not comparable between companies of different sizes. Negative working capital is normal in businesses paid before they pay suppliers.",
    denominatorMustBePositive: false,
  },
  {
    key: "ocf_to_current_liabilities",
    family: "liquidity",
    label: "Operating cash flow to current liabilities",
    expression: "cash_from_operations / total_current_liabilities",
    unit: "x",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Cash generated by operations divided by current liabilities. Asks how much of what is due within a year the business produces in cash over a year, rather than what it happens to hold on the balance-sheet date.",
    caveat:
      "A single period of operating cash flow can be distorted by a one-off working-capital swing.",
    denominatorMustBePositive: false,
  },

  // ---- Leverage ----
  {
    key: "debt_to_equity",
    family: "leverage",
    label: "Debt to equity",
    expression: `${TOTAL_DEBT} / total_equity`,
    unit: "x",
    direction: "lower",
    isCore: true,
    dayScaled: false,
    definition:
      "Short-term plus long-term borrowings divided by shareholders' equity. How much of the capital structure is lenders' money against owners' money.",
    caveat:
      "Excludes operating leases and pension obligations, which are real claims. Buybacks shrink equity and inflate this figure without new borrowing.",
    denominatorMustBePositive: true,
  },
  {
    key: "debt_to_assets",
    family: "leverage",
    label: "Debt to assets",
    expression: `${TOTAL_DEBT} / total_assets`,
    unit: "percent",
    direction: "lower",
    isCore: false,
    dayScaled: false,
    definition:
      "Total borrowings as a percentage of total assets. What share of everything the company controls was funded by debt.",
    caveat:
      "Assets are carried at book value, so an asset-light or long-held-property business is not comparable with a recently acquisitive one.",
    denominatorMustBePositive: false,
  },
  {
    key: "liabilities_to_equity",
    family: "leverage",
    label: "Liabilities to equity",
    expression: "total_liabilities / total_equity",
    unit: "x",
    direction: "lower",
    isCore: false,
    dayScaled: false,
    definition:
      "All liabilities, not only borrowings, divided by equity. Captures payables, deferred revenue and accruals that debt-to-equity ignores.",
    caveat:
      "Deferred revenue is a liability that usually signals demand rather than distress, so a rising figure is not automatically worse.",
    denominatorMustBePositive: false,
  },
  {
    key: "equity_multiplier",
    family: "leverage",
    label: "Equity multiplier",
    expression: "total_assets / total_equity",
    unit: "x",
    direction: "context",
    isCore: false,
    dayScaled: false,
    definition:
      "Total assets divided by equity. The leverage term of the DuPont decomposition: how many currency units of assets each unit of equity supports.",
    caveat:
      "Leverage raises returns and risk together. Reading a rising multiplier as improving performance is the mistake DuPont exists to prevent.",
    denominatorMustBePositive: false,
  },
  {
    key: "net_debt_to_ebitda",
    family: "leverage",
    label: "Net debt to EBITDA",
    expression: `(${TOTAL_DEBT} - cash_and_equivalents - short_term_investments) / ${EBITDA}`,
    unit: "x",
    direction: "lower",
    isCore: false,
    dayScaled: false,
    definition:
      "Borrowings less cash and marketable securities, divided by operating income plus depreciation and amortisation. Roughly how many years of current earnings would repay the net borrowings, and the covenant most credit agreements are written against.",
    caveat:
      "EBITDA ignores the capital spending needed to sustain those earnings, so it flatters capital-intensive businesses.",
    denominatorMustBePositive: true,
  },

  // ---- Efficiency ----
  {
    key: "dso",
    family: "efficiency",
    label: "Days sales outstanding",
    expression: "accounts_receivable / revenue",
    unit: "days",
    direction: "lower",
    isCore: true,
    dayScaled: true,
    definition:
      "Receivables divided by revenue, expressed in days. How long, on average, the company waits to be paid after making a sale.",
    caveat:
      "Compares a balance measured on one date against a flow earned over a period, so a seasonal year-end distorts it.",
    denominatorMustBePositive: false,
  },
  {
    key: "dio",
    family: "efficiency",
    label: "Days inventory outstanding",
    expression: "inventory / cost_of_revenue",
    unit: "days",
    direction: "lower",
    isCore: true,
    dayScaled: true,
    definition:
      "Inventory divided by cost of revenue, expressed in days. How long stock sits before it is sold.",
    caveat:
      "Meaningless for a business that carries no inventory, and distorted by a build-up ahead of a product launch.",
    denominatorMustBePositive: false,
  },
  {
    key: "dpo",
    family: "efficiency",
    label: "Days payable outstanding",
    expression: "accounts_payable / cost_of_revenue",
    unit: "days",
    direction: "context",
    isCore: false,
    dayScaled: true,
    definition:
      "Payables divided by cost of revenue, expressed in days. How long the company takes to pay its own suppliers.",
    caveat:
      "Stretching payment terms improves cash flow and strains supplier relationships. Higher is not straightforwardly better.",
    denominatorMustBePositive: false,
  },
  {
    key: "cash_conversion_cycle",
    family: "efficiency",
    label: "Cash conversion cycle",
    expression: "dso + dio - dpo",
    unit: "days",
    direction: "lower",
    isCore: false,
    dayScaled: false,
    definition:
      "Days sales outstanding plus days inventory outstanding less days payable outstanding. The number of days cash is tied up in the operating cycle between paying for stock and collecting for it.",
    caveat:
      "Inherits every distortion of its three components. A negative cycle is a real advantage, not an error.",
    denominatorMustBePositive: false,
  },
  {
    key: "asset_turnover",
    family: "efficiency",
    label: "Asset turnover",
    expression: "revenue / total_assets",
    unit: "x",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Revenue divided by total assets. How much sales each unit of assets generates, and the efficiency term of the DuPont decomposition.",
    caveat:
      "Book-value assets fall with depreciation, so an ageing asset base raises this figure without any operating improvement.",
    denominatorMustBePositive: false,
  },

  // ---- Profitability ----
  {
    key: "gross_margin",
    family: "profitability",
    label: "Gross margin",
    expression: "gross_profit / revenue",
    unit: "percent",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Gross profit as a percentage of revenue. What is left of each sale after the direct cost of delivering it, and the ceiling on every margin below.",
    caveat:
      "What sits in cost of revenue rather than operating expenses varies between companies, so cross-company comparison needs care.",
    denominatorMustBePositive: false,
  },
  {
    key: "operating_margin",
    family: "profitability",
    label: "Operating margin",
    expression: "operating_income / revenue",
    unit: "percent",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Operating income as a percentage of revenue. Profitability of the core business before financing and tax, which makes it the cleanest comparison between companies with different capital structures.",
    caveat:
      "Restructuring charges and impairments sit here and can make one period look structurally worse than it is.",
    denominatorMustBePositive: false,
  },
  {
    key: "net_margin",
    family: "profitability",
    label: "Net margin",
    expression: "net_income / revenue",
    unit: "percent",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Net income as a percentage of revenue. What reaches shareholders from each unit of sales after every cost, including interest and tax.",
    caveat:
      "Moves with one-off tax items and gains on disposals, so a jump here without a matching move in operating margin is usually not operational.",
    denominatorMustBePositive: false,
  },
  {
    key: "ebitda_margin",
    family: "profitability",
    label: "EBITDA margin",
    expression: `${EBITDA} / revenue`,
    unit: "percent",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Operating income plus depreciation and amortisation, as a percentage of revenue. A rough cash-profitability measure that removes the effect of differing depreciation policies.",
    caveat:
      "Depreciation is a real cost deferred, not a cost avoided. EBITDA margin overstates profitability for anything capital-intensive.",
    denominatorMustBePositive: false,
  },
  {
    key: "roa",
    family: "profitability",
    label: "Return on assets",
    expression: "net_income / total_assets",
    unit: "percent",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Net income as a percentage of total assets. How much profit the asset base produces, regardless of how it was funded.",
    caveat:
      "Net income is after interest, so a heavily indebted company is penalised twice here. Goodwill from acquisitions depresses it without any operating change.",
    denominatorMustBePositive: false,
  },
  {
    key: "roe",
    family: "profitability",
    label: "Return on equity",
    expression: "net_income / total_equity",
    unit: "percent",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Net income as a percentage of shareholders' equity. The return earned on owners' capital, and the figure DuPont decomposes into margin, turnover and leverage.",
    caveat:
      "Buybacks shrink equity and raise this without the business improving. A company with negative equity produces a figure that cannot be read at all.",
    denominatorMustBePositive: true,
  },

  // ---- Coverage ----
  {
    key: "interest_coverage",
    family: "coverage",
    label: "Interest coverage",
    expression: "operating_income / interest_expense",
    unit: "x",
    direction: "higher",
    isCore: true,
    dayScaled: false,
    definition:
      "Operating income divided by interest expense. How many times over the core business covers the cost of its borrowings in a period.",
    caveat:
      "Operating income is not cash. A company can cover interest on paper while short of the cash to pay it.",
    denominatorMustBePositive: true,
  },
  {
    key: "ebitda_interest_coverage",
    family: "coverage",
    label: "EBITDA interest coverage",
    expression: `${EBITDA} / interest_expense`,
    unit: "x",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Operating income plus depreciation and amortisation, divided by interest expense. The coverage test lenders usually write, on the view that non-cash charges do not compete with the interest payment.",
    caveat:
      "Always flatters the picture against plain interest coverage. Read the gap between the two rather than this figure alone.",
    denominatorMustBePositive: false,
  },
  {
    key: "cfo_to_debt",
    family: "coverage",
    label: "Operating cash flow to debt",
    expression: `cash_from_operations / ${TOTAL_DEBT}`,
    unit: "percent",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Cash from operations as a percentage of total borrowings. What share of the debt a year of operating cash could repay, using cash rather than accounting profit.",
    caveat:
      "Ignores that most of the debt is not due this year. A low figure is not a repayment problem on its own.",
    denominatorMustBePositive: false,
  },
  {
    key: "capex_coverage",
    family: "coverage",
    label: "Capex coverage",
    expression: "cash_from_operations / capital_expenditures",
    unit: "x",
    direction: "higher",
    isCore: false,
    dayScaled: false,
    definition:
      "Cash from operations divided by capital expenditure. Whether the business funds its own investment, or has to raise money to do it. Below 1.0x means the shortfall came from debt, equity or the cash balance.",
    caveat:
      "Capital spending is lumpy. A single year below 1.0x during a plant build is expected rather than alarming.",
    denominatorMustBePositive: false,
  },
];

export const CORE_KEYS: readonly string[] = RATIOS.filter((r) => r.isCore).map((r) => r.key);

const BY_KEY = new Map(RATIOS.map((r) => [r.key, r]));

export function ratio(key: string): RatioDef | undefined {
  return BY_KEY.get(key);
}

export function ratiosFor(family: RatioFamily): RatioDef[] {
  return RATIOS.filter((r) => r.family === family);
}
